variable "aws_access_key" {} 
variable "aws_secret_key" {}
variable "aws_region" {}
variable "cidr_range" {} 
  //variable "subnet_range" {}
   //variable "availability_zone_code" {}
variable "region_code" {}
 variable "project_name" {} 
 variable "flag" {} 